# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "folia" ]
  pull_request:
    branches: [ "folia" ]

jobs:
  build:
    name: build jar
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'zulu'
  
    - name: checkout current repo
      uses: actions/checkout@v4
      with:
        path: 'workspace/LevelledMobs'

    - name: checkout KujouMolean/FoliaAdapter
      uses: actions/checkout@v4
      with:
        repository: 'KujouMolean/FoliaAdapter'
        path: 'workspace/FoliaAdapter'

    - name: run maven install at FoliaAdapter
      run: cd workspace/FoliaAdapter && ./gradlew publishToMavenLocal

    - name: build LevelledMobs
      run: cd workspace/LevelledMobs && ./gradlew build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: workspace/LevelledMobs/levelledmobs-plugin/build/libs/

